org.gradle.jvmargs = -Xmx2G

# Mod Info
archives_base_name = mpt
mod_version = 0.0.1
maven_group = dev.mpt

minecraft_version = 1.20.1
enabled_platforms = fabric,forge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2023.09.03

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version = 0.16.9
fabric_api_version = 0.92.0+1.20.1

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version = 47.2.6

# Create - Fabric
# https://modrinth.com/mod/create-fabric/versions
create_fabric_version = 0.5.1-j-build.1631+mc1.20.1

# Create - Forge
# https://github.com/Creators-of-Create/Create/wiki/Depending-on-Create
create_forge_version = 6.0.6-163
ponder_forge_version = 1.0.80

# Fabric recipe viewers
fabric_recipe_viewer = EMI
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.2.0.22
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.18+1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.1.0

# Fzzy Config
fzzy_config_version = 0.7.0+1.20.1